-- Cover + example realization photos that the owner uploads from /admin/dywany.
--
-- Until now every gallery photo lived in lib/gallery.ts and public/ruggy, so a
-- new category added from the panel had no way to show anything. Photos now go
-- to Supabase Storage and are listed here; lib/rug-photos.ts falls back to the
-- curated static set for any category that has no rows yet, so the existing
-- categories keep their current photos untouched.

create table if not exists public.rug_photos (
  id bigint generated by default as identity primary key,
  rug_type_id bigint not null references public.rug_types(id) on delete cascade,
  storage_path text not null unique,
  is_cover boolean not null default false,
  display_order bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists rug_photos_rug_type_id_idx
  on public.rug_photos (rug_type_id, display_order);

-- The card cover is one specific photo, not "whichever row sorts first".
create unique index if not exists rug_photos_one_cover_per_type_idx
  on public.rug_photos (rug_type_id)
  where is_cover;

alter table public.rug_photos enable row level security;

-- Anyone browsing the shop reads them; only the service role (the admin panel's
-- server actions) writes.
drop policy if exists "Public can read rug photos" on public.rug_photos;
create policy "Public can read rug photos"
  on public.rug_photos
  for select
  to anon, authenticated
  using (true);

-- Public bucket on purpose: these URLs are baked into ISR-cached pages, and a
-- signed URL would expire while the page is still being served from cache.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'rug-catalog-photos',
  'rug-catalog-photos',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
