create table if not exists public.rug_variants (
  id bigint generated by default as identity primary key,
  rug_type_id bigint not null references public.rug_types(id) on delete cascade,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  display_order bigint not null default 0,
  created_at timestamptz not null default now(),
  unique (rug_type_id, slug)
);

alter table public.rug_sizes
  alter column rug_type_id drop not null,
  add column if not exists rug_variant_id bigint references public.rug_variants(id) on delete cascade;

alter table public.bookings
  add column if not exists rug_variant_id bigint references public.rug_variants(id) on delete set null,
  add column if not exists rug_variant_name text,
  alter column rug_size_id drop not null,
  alter column stripe_session_id drop not null,
  alter column stripe_payment_intent_id drop not null,
  alter column expires_at drop not null;

create index if not exists rug_variants_rug_type_id_idx
  on public.rug_variants (rug_type_id, display_order);

create index if not exists rug_sizes_rug_variant_id_idx
  on public.rug_sizes (rug_variant_id, display_order);

create index if not exists bookings_status_booking_date_idx
  on public.bookings (status, booking_date);

alter table public.rug_variants enable row level security;

drop policy if exists "Public can read active rug variants" on public.rug_variants;
create policy "Public can read active rug variants"
  on public.rug_variants
  for select
  to anon, authenticated
  using (is_active = true);
